### ISSUE TITLE
How to use this ?

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo-Controller#2]
First I ran the run of controller and closed it after building process.. Then I started CS:GO , Had a weapon in hand started abendigo and then this controller .. now What are the hotkeys ? When I press F9 a empty menu shows up

**Comment by Jire** [comment]
You need to have the driver (server) running before the controller (client).

**Comment by punkjj** [comment]
wait a min "driver" = "Abendigo-Master" and controller = "Abendigo-controller-master" ??

**Comment by Jire** [comment]
You're right! The driver is https://github.com/Jire/Abendigo and the controller is this repository. Also, I think this video will be a big help :smiley: 

https://www.youtube.com/watch?v=kAiQj6gBvl0
